### ISSUE TITLE
android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=21, totalRows=22

### ISSUE THREAD

**Issue by xinyitiandi** [leavesCZY/Monitor#8]
Process: com.iguopin.app, PID: 7042
                                                                                                    android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=21, totalRows=22
                                                                                                    	at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
                                                                                                    	at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:986)
                                                                                                    	at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:858)
                                                                                                    	at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
                                                                                                    	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:161)
                                                                                                    	at android.database.sqlite.SQLiteCursor.onMove(SQLiteCursor.java:131)
                                                                                                    	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:249)
                                                                                                    	at android.database.AbstractCursor.moveToNext(AbstractCursor.java:281)
                                                                                                    	at github.leavesczy.monitor.db.MonitorDao_Impl$6.call(MonitorDao_Impl.java:507)
                                                                                                    	at github.leavesczy.monitor.db.MonitorDao_Impl$6.call(MonitorDao_Impl.java:478)

**Comment by SOCK-MAGIC** [comment]
@leavesCZY

**Comment by leavesCZY** [comment]
@xinyitiandi 是否有具体的复现步骤呢？发生该问题所需的条件是什么
